### ISSUE TITLE
Debug Session Ended: failed to launch target 

### ISSUE THREAD

**Issue by grassel** [koush/quickjs#1]
Hi!

Potentially very useful work. Thank you.
Please try help me getting things to work.

In VSC Debug Console I am seeing the following error message upon launching a Debug session

```
QuickJS Debug Port: 34449
Debug Session Ended: failed to launch target (Error: spawn /home/grassel/sources/quickjs-debug/qjs ENOENT)
Debug Session Ended: target closed
```
I installed the extension to VSC and created a task in my project's launch.json.

```
 "configurations": [
        {
            "type": "quickjs",
            "request": "launch",
            "name": "Launch QuickJS",
            "runtimeExecutable": "/home/grassel/sources/quickjs-debug/qjs",
            "program": "^\"${workspaceFolder}/hello.js\""
        }
    ]
}
```

I took the latest code of your QJS fork and built it with make 
```/home/grassel/sources/quickjs-debug/qjs``` exists. It launches the familiar interactive debug console.  I am on Ubuntu 18.04 , using gcc compiler.

Thanks!
- Guido

**Comment by koush** [comment]
I'll double check linux.

Your program shoud look like this:

```json
            "program": "${workspaceFolder}/main.js",
```

There may be an issue with the how the default launch.json template is constructed if that's what it suggested.

I suspect the ENOENT is caused by it not being able to find the file.

**Comment by koush** [comment]
Here's the minimal config I use:

```js
        {
            "type": "quickjs",
            "request": "launch",
            "name": "Launch QuickJS CLI",
            "runtimeExecutable": "${workspaceFolder}/../../quickjs/qjs-debug",
            "program": "${workspaceFolder}/test3.js",
        }
```

**Comment by grassel** [comment]
Thanks guys. - yes, the last property ```program``` had a stupid copy paste issue (escaped quotes.).
