### ISSUE TITLE
Without DIRECT_DISPATCH

### ISSUE THREAD

**Issue by chmeyer-ms** [koush/quickjs#12]
Calling `js_debugger_check(ctx, NULL)` for each op code when not using `DIRECT_DISPATCH` doesn't work. Suggest moving it out of the `for(;;)` so that it behaves the same as in DD mode, which does not use the `for(;;)` since it jumps from goto to goto until the op stream is complete.

```
js_debugger_check(ctx, NULL); // <-- move out of for loop

for(;;) {
        int call_argc;
        JSValue *call_argv;

        //js_debugger_check(ctx, NULL); // <-- shouldn't call this each iteration

        SWITCH(pc) {
        CASE(OP_push_i32):
            *sp++ = JS_NewInt32(ctx, get_u32(pc));
            pc += 4;
            BREAK;
```

**Comment by koush** [comment]
It's necessary.

f0989ea83e84fb0d82faa725a1f1eed2fb361738
