### ISSUE TITLE
Can not hit breakpoint at the end of function

### ISSUE THREAD

**Issue by pengyz** [koush/quickjs#13]
js_debugger_check_breakpoint will always return false if the breakpoint is at the end of the function.

**Comment by koush** [comment]
yeah I am unsure why tail calls don't break. feel free to figure it out.

**Comment by pengyz** [comment]
> yeah I am unsure why tail calls don't break. feel free to figure it out.

I fixed it. It's a bug of original quickjs. It do not generate pc2line info for the last line.

I'll push my fix later.

**Comment by pengyz** [comment]
I make a PR #14 to fix this and some other issue.

I wonder if we should push it to the upstream.

**Comment by koush** [comment]
yes please push upstream
