### ISSUE TITLE
A better way to handle debug message

### ISSUE THREAD

**Issue by pengyz** [koush/quickjs#17]
I'm sorry for my poor english.

The debugger message is processed during engine interpretered the js bytecode.
If the jscode is not execute, the debug message will not be handled, it's not good enough for me: I will implement more debugging things and hope debugger response quickly.

I use libuv for event loop and want quickjs debug message be handled in it.
I changed the debug message handle logic to allow libuv timer event to trigger it. If needed, I can make a PR for my changes.

**Comment by koush** [comment]
Yes, that is how you should manage debugger messages, on an event loop. quickjs does not provide an event loop and we should not introduce such dependencies into this project.

**Comment by koush** [comment]
To clarify, periodically calling 
`void js_debugger_cooperate(JSContext *ctx);`
is up to the quickjs embedder.
