### ISSUE TITLE
How to setup the debugger support in C/C++ 

### ISSUE THREAD

**Issue by Geequlim** [koush/quickjs#2]
Any documentation for how to enable the debugger in a program with QuickJS embedded ?

**Comment by koush** [comment]
See here:

https://github.com/koush/quickjs/blob/master/quickjs-debugger.h#L67

To listen for a connection in embedded quickjs (attach + connect with vscode debugger):
```c
// address is in format "0.0.0.0:6666" to listen on all addresses on port 6666
void js_debugger_wait_connection(JSContext *ctx, const char* address);
```


To initiate a connection in embedded quickjs (attach + listen with vscode debugger):
```c
// address is in format "192.168.1.66:6666" to connect to 192.168.1.66 on port 6666
void js_debugger_connect(JSContext *ctx, const char* address);
```

This will block execution until the connection is complete.

**Comment by koush** [comment]
Alternatively, provide one of the following environment variables before starting the process:

`QUICKJS_DEBUG_ADDRESS` or `QUICKJS_DEBUG_LISTEN_ADDRESS` with the same value as above.

When the quickjs context is created, it will block execution and attempt to connect.
