### ISSUE TITLE
Reason for js_debugger_check with `cur_pc` = `NULL`

### ISSUE THREAD

**Issue by juancampa** [koush/quickjs#24]
Hi @koush,

I've been porting your debugger (amazing btw) to my fork of QuickJS. I noticed that stepping was wonky for some reason. I might have broken it while porting it though. 

To fix it I had to remove this line:

https://github.com/koush/quickjs/blob/master/quickjs.c#L16349

Which calls `js_debugger_check` with a `cur_pc=NULL`. This line causes the debugger to jump back to the start of the function on every other step, and then back to the right line on the next. 

If you happen to remember the reason, what's the purpose of calling `js_debugger_check` with no PC?

**Comment by juancampa** [comment]
It seems like that line was last changed in this commit:

https://github.com/koush/quickjs/commit/f0989ea83e84fb0d82faa725a1f1eed2fb361738

```
Debugger: perform the debugger check after the new call frame is ready. Fixes breakpoints on tail calls.
```

**Comment by koush** [comment]
I don’t unfortunately. May have been specific to that version of quick js

**Comment by juancampa** [comment]
It's all good. I'll post here if I figure it out.
