### ISSUE TITLE
What license does this project applied？

### ISSUE THREAD

**Issue by ppshw** [koush/quickjs#4]

**Comment by koush** [comment]
Apache.

**Comment by koush** [comment]
I'll add it.

**Comment by past-due** [comment]
@koush: Would you be willing to consider licensing under the MIT License, like QuickJS itself is?

(There are some other licenses - ex. GPLv2 - that are unfortunately incompatible with the Apache license, but _are_ compatible with the MIT License.)

Thank you for the consideration. This is a fantastic project.

**Comment by koush** [comment]
Sure.

**Comment by koush** [comment]
License added.
