### ISSUE TITLE
Too long to enter break point in real project

### ISSUE THREAD

**Issue by Geequlim** [koush/quickjs#8]
I‘m trying to integrate this debugger into my godot game engine binding. I have registered hundreds of classes from C++ to QuickJS. These classes are registered in `globalThis.godot`. It takes more than two minutes to enter the breakpoint.

**Comment by Geequlim** [comment]
This value could be configerable.
https://github.com/koush/quickjs/blob/5f9d3145776d040100ab736450c94c21cddedb6c/quickjs-debugger.c#L635

**Comment by koush** [comment]
Feel free to submit a submit request. breakpoints are only guaranteed while execution is paused.
