### ISSUE TITLE
Support inspect __proto__ ?

### ISSUE THREAD

**Issue by Geequlim** [koush/quickjs#9]
Thanks for your debugger implementation. I ported it to my [Godot Engine binding]()
The objects can only inspect values defined with own peroperties. It would be greate to inspector the `__proto__` to check properties from native parent classes.

Here is the example with V8 in Chrome for the performance object.
![image](https://user-images.githubusercontent.com/6964556/89781032-2056b080-db45-11ea-81d7-02a66fc96498.png)

**Comment by koush** [comment]
d85b25c
